<?xml version="1.0" encoding="UTF-8"?>

<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dwarfeng</groupId>
        <artifactId>notify</artifactId>
        <version>3.0.0.a-SNAPSHOT</version>
    </parent>

    <packaging>pom</packaging>

    <artifactId>notify-node</artifactId>
    <name>notify-node</name>
    <url>http://maven.apache.org</url>

    <properties>
        <!-- 进行工程编码声明 -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>notify-node-all-he</module>
    </modules>
</project>
