com.dwarfeng.notify.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.notify.jdbc.url=jdbc:mysql://your-host-here:3306/notify?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.notify.jdbc.username=root
com.dwarfeng.notify.jdbc.password=your-password-here
com.dwarfeng.notify.hibernate.dialect=org.hibernate.dialect.MySQLDialect
